version: '3.8'
services:
  tomcat:
    image: tomcat:10.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/TrainingProjectT1-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/TrainingProjectT1-1.0-SNAPSHOT.war
    restart: on-failure